
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'TestGaoDeMap.xcodeproj'

inhibit_all_warnings!

platform :ios, '7.0'

pod 'AMapSearch', '3.0.0'
pod 'AMapNavi'  #导航，包含AMap3DMap
#pod 'AMapCloudMap'